#!/usr/bin/env bash
#
# Installs AgentRecall as a global .NET tool and registers its MCP server with
# Claude Code. Generated by `agentrecall devcontainer init`.
#
# "Rebuild Container" discards the container filesystem, so the globally-installed
# tool (~/.dotnet/tools) and the MCP registration (~/.claude/.claude.json) are
# rebuilt here on every create. The SQLite database survives separately on the
# named `agentrecall-data` Docker volume.
set -euo pipefail

TOOLS_DIR="$HOME/.dotnet/tools"

# Where AgentRecall stores its database. Matches the devcontainer.json mount and
# env; falls back to the per-user default when that env var isn't set.
DATA_DIR="${AGENTRECALL_AgentRecall__DataDirectory:-$HOME/.agentrecall}"

# Name each step and, on failure, say which command aborted the script and that
# AgentRecall was not installed — so a rebuild failure is easy to diagnose
# instead of surfacing later as a confusing "command not found".
STEP="startup"
log()  { echo "==> $1"; STEP="$1"; }
trap 'code=$?; echo "" >&2; echo "AgentRecall: setup FAILED during: $STEP (exit $code)." >&2; echo "AgentRecall: the tool was NOT installed; fix the error above and rebuild, or" >&2; echo "             run \"bash .devcontainer/agentrecall-post-create.sh\" to retry." >&2' ERR

# A named Docker volume mounts root-owned on first create, so a non-root container
# user can't write to it. Make it writable using whatever the image actually
# offers (we may already be root, or have sudo, or neither) — best effort, never
# fatal, and never assuming `sudo` exists.
log "ensure data directory is writable"
ensure_writable() {
  mkdir -p "$DATA_DIR" 2>/dev/null || true
  [ -w "$DATA_DIR" ] && return 0
  if [ "$(id -u)" = "0" ]; then
    chown -R "$(id -u):$(id -g)" "$DATA_DIR" 2>/dev/null || true
  elif command -v sudo >/dev/null 2>&1; then
    sudo chown -R "$(id -u):$(id -g)" "$DATA_DIR" 2>/dev/null || true
  fi
  if [ ! -w "$DATA_DIR" ]; then
    echo "AgentRecall: $DATA_DIR is not writable by $(id -un), and this image" \
         "offers no way to fix it (not root, no sudo)." >&2
    echo "AgentRecall: add sudo to the image, set \"remoteUser\": \"root\", or" \
         "chown the volume in your Dockerfile, then rebuild." >&2
  fi
}
ensure_writable

# Make ~/.dotnet/tools discoverable. VS Code often starts bash as a NON-login
# shell, so ~/.profile isn't sourced and a global tool reads as "not found" even
# when installed. Put it on PATH for this shell and persist to ~/.bashrc
# (idempotent), and print the exact remoteEnv snippet.
log "ensure $TOOLS_DIR is on PATH"
case ":$PATH:" in
  *":$TOOLS_DIR:"*)
    : # already on PATH for this shell
    ;;
  *)
    if ! { [ -f "$HOME/.bashrc" ] && grep -qF "$TOOLS_DIR" "$HOME/.bashrc"; }; then
      printf '\n# Added by AgentRecall: put .NET global tools on PATH for non-login shells\nexport PATH="$PATH:%s"\n' "$TOOLS_DIR" >> "$HOME/.bashrc" 2>/dev/null \
        && echo "AgentRecall: appended a PATH export to ~/.bashrc for new terminals." >&2
    fi
    echo "AgentRecall: to set PATH for VS Code permanently, add to .devcontainer/devcontainer.json:" >&2
    echo "             \"remoteEnv\": { \"PATH\": \"\${containerEnv:PATH}:$TOOLS_DIR\" }" >&2
    ;;
esac
export PATH="$PATH:$TOOLS_DIR"

# Resolve the agentrecall binary: on PATH, or freshly installed under TOOLS_DIR.
find_agentrecall() {
  command -v agentrecall 2>/dev/null && return 0
  [ -x "$TOOLS_DIR/agentrecall" ] && { printf '%s\n' "$TOOLS_DIR/agentrecall"; return 0; }
  return 1
}

# Self-healing install. A rebuild wipes ~/.dotnet/tools while the MCP registration
# can persist on a volume. If the binary is missing we try to REPAIR it before
# touching the registration; only if repair fails do we remove the stale entry.
# The reinstall is guarded by `if`, so a failure never trips `set -e`/the ERR trap
# and never blocks container startup — we fall through to cleanup instead.
log "ensure AgentRecall is installed (self-heal if missing)"
AGENTRECALL_BIN="$(find_agentrecall || true)"
if [ -n "$AGENTRECALL_BIN" ]; then
  echo "    (agentrecall present at $AGENTRECALL_BIN; no reinstall needed)"
else
  echo "AgentRecall: binary missing; attempting reinstall: dotnet tool update --global AgentRecall" >&2
  if dotnet tool update --global AgentRecall; then
    AGENTRECALL_BIN="$(find_agentrecall || true)"
  else
    echo "AgentRecall: reinstall command exited non-zero ($?)." >&2
  fi
fi

if [ -n "$AGENTRECALL_BIN" ]; then
  # Repaired (or never broken). Initialize the DB and (re-)register the MCP server
  # by ABSOLUTE path so Claude Code starts it regardless of its spawn PATH.
  log "initialize the database"
  "$AGENTRECALL_BIN" init || echo "AgentRecall: 'agentrecall init' failed; see the warning above." >&2

  log "register the MCP server with Claude Code"
  if command -v claude >/dev/null 2>&1; then
    claude mcp remove agentrecall >/dev/null 2>&1 || true
    claude mcp add agentrecall "$AGENTRECALL_BIN" mcp 2>/dev/null \
      && echo "AgentRecall: MCP server registered ($AGENTRECALL_BIN)." \
      || echo "AgentRecall: 'claude mcp add' failed; register manually: claude mcp add agentrecall \"$AGENTRECALL_BIN\" mcp" >&2
  else
    echo "    (claude CLI not found; skipping MCP registration)"
  fi

  echo "AgentRecall ready: $("$AGENTRECALL_BIN" --version 2>/dev/null || echo 'unknown')"
else
  # Repair failed. Remove the stale registration so Claude Code does not try to
  # start a server whose binary is missing, explain why, and continue (non-fatal).
  log "remove stale MCP registration (repair failed)"
  if command -v claude >/dev/null 2>&1; then
    claude mcp remove agentrecall >/dev/null 2>&1 || true
  fi
  echo "AgentRecall: reinstall failed and the binary is still missing." >&2
  echo "             Removed any stale MCP registration so Claude Code won't start a" >&2
  echo "             missing server. Fix the install with:" >&2
  echo "               dotnet tool update --global AgentRecall" >&2
  echo "             then rerun: bash .devcontainer/agentrecall-post-create.sh" >&2
  echo "AgentRecall: not operational (binary missing); see the warnings above."
fi
