namespace AgentRecall.Cli.Devcontainer;

/// <summary>
/// Scaffolds the dev container wiring that reinstalls AgentRecall on every
/// "Rebuild Container". A rebuild discards the container filesystem, so the
/// globally-installed tool and its Claude Code MCP registration are lost; the
/// generated <c>postCreateCommand</c> script rebuilds them while the SQLite
/// database survives on a named Docker volume.
/// </summary>
public static class DevcontainerScaffolder
{
    /// <summary>Named Docker volume that backs the persisted database directory.</summary>
    public const string DataVolumeName = "agentrecall-data";

    /// <summary>Container path the data volume mounts at, and that the CLI is pinned to.</summary>
    public const string DataDirectory = "/home/vscode/.agentrecall";

    /// <summary>Path, relative to the project root, of the generated setup script.</summary>
    public const string PostCreateRelativePath = ".devcontainer/agentrecall-post-create.sh";

    /// <summary>Path, relative to the project root, of the dev container manifest.</summary>
    public const string DevcontainerJsonRelativePath = ".devcontainer/devcontainer.json";

    /// <summary>
    /// The self-contained setup script. Installs AgentRecall from NuGet, pins the
    /// data directory onto the persisted volume, and re-registers the MCP server.
    /// Idempotent, so it is safe to re-run on every create/rebuild.
    /// </summary>
    public static string PostCreateScript =>
        """
        #!/usr/bin/env bash
        #
        # Installs AgentRecall as a global .NET tool and registers its MCP server with
        # Claude Code. Generated by `agentrecall devcontainer init`.
        #
        # "Rebuild Container" discards the container filesystem, so the globally-installed
        # tool (~/.dotnet/tools) and the MCP registration (~/.claude/.claude.json) are
        # rebuilt here on every create. The SQLite database survives separately on the
        # named `agentrecall-data` Docker volume.
        set -euo pipefail

        TOOLS_DIR="$HOME/.dotnet/tools"

        # Where AgentRecall stores its database. Matches the devcontainer.json mount and
        # env; falls back to the per-user default when that env var isn't set.
        DATA_DIR="${AGENTRECALL_AgentRecall__DataDirectory:-$HOME/.agentrecall}"

        # Name each step and, on failure, say which command aborted the script and that
        # AgentRecall was not installed — so a rebuild failure is easy to diagnose
        # instead of surfacing later as a confusing "command not found".
        STEP="startup"
        log()  { echo "==> $1"; STEP="$1"; }
        trap 'code=$?; echo "" >&2; echo "AgentRecall: setup FAILED during: $STEP (exit $code)." >&2; echo "AgentRecall: the tool was NOT installed; fix the error above and rebuild, or" >&2; echo "             run \"bash .devcontainer/agentrecall-post-create.sh\" to retry." >&2' ERR

        # A named Docker volume mounts root-owned on first create, so a non-root container
        # user can't write to it. Make it writable using whatever the image actually
        # offers (we may already be root, or have sudo, or neither) — best effort, never
        # fatal, and never assuming `sudo` exists.
        log "ensure data directory is writable"
        ensure_writable() {
          mkdir -p "$DATA_DIR" 2>/dev/null || true
          [ -w "$DATA_DIR" ] && return 0
          if [ "$(id -u)" = "0" ]; then
            chown -R "$(id -u):$(id -g)" "$DATA_DIR" 2>/dev/null || true
          elif command -v sudo >/dev/null 2>&1; then
            sudo chown -R "$(id -u):$(id -g)" "$DATA_DIR" 2>/dev/null || true
          fi
          if [ ! -w "$DATA_DIR" ]; then
            echo "AgentRecall: $DATA_DIR is not writable by $(id -un), and this image" \
                 "offers no way to fix it (not root, no sudo)." >&2
            echo "AgentRecall: add sudo to the image, set \"remoteUser\": \"root\", or" \
                 "chown the volume in your Dockerfile, then rebuild." >&2
          fi
        }
        ensure_writable

        # Install or upgrade AgentRecall from NuGet. `tool update` installs when absent
        # and upgrades when present, so it is safe to re-run on every rebuild.
        log "install/upgrade AgentRecall from NuGet"
        dotnet tool update --global AgentRecall

        # Make ~/.dotnet/tools discoverable in interactive terminals. VS Code often starts
        # bash as a NON-login shell, so ~/.profile isn't sourced and a freshly installed
        # global tool reads as "not found" even though the install succeeded. Persist the
        # PATH entry to ~/.bashrc (idempotent) and print the exact remoteEnv snippet.
        log "ensure $TOOLS_DIR is on PATH"
        case ":$PATH:" in
          *":$TOOLS_DIR:"*)
            : # already on PATH for this shell
            ;;
          *)
            echo "AgentRecall: $TOOLS_DIR is not on PATH; the tool may be 'not found' in new terminals." >&2
            if ! { [ -f "$HOME/.bashrc" ] && grep -qF "$TOOLS_DIR" "$HOME/.bashrc"; }; then
              printf '\n# Added by AgentRecall: put .NET global tools on PATH for non-login shells\nexport PATH="$PATH:%s"\n' "$TOOLS_DIR" >> "$HOME/.bashrc" 2>/dev/null \
                && echo "AgentRecall: appended a PATH export to ~/.bashrc for new terminals." >&2
            fi
            echo "AgentRecall: to set it permanently for VS Code, add to .devcontainer/devcontainer.json:" >&2
            echo "             \"remoteEnv\": { \"PATH\": \"\${containerEnv:PATH}:$TOOLS_DIR\" }" >&2
            ;;
        esac
        export PATH="$PATH:$TOOLS_DIR"

        # Create the database (no-op when it already exists on the volume). Warn rather
        # than abort, so a not-yet-writable volume doesn't fail the whole postCreate chain.
        log "initialize the database"
        agentrecall init || echo "AgentRecall: 'agentrecall init' failed; see the warning above." >&2

        # Re-register the MCP server with Claude Code, if the CLI is installed.
        log "register the MCP server with Claude Code"
        if command -v claude >/dev/null 2>&1; then
          claude mcp add agentrecall agentrecall mcp 2>/dev/null || true
        else
          echo "    (claude CLI not found; skipping MCP registration)"
        fi

        echo "AgentRecall ready: $(agentrecall --version 2>/dev/null || echo 'install failed')"

        """;

    /// <summary>
    /// A complete <c>devcontainer.json</c> generated only when the project has none.
    /// </summary>
    public static string DevcontainerJson =>
        """
        {
          // Dev container with AgentRecall preinstalled. Generated by
          // `agentrecall devcontainer init`.
          "name": "AgentRecall-enabled",
          "image": "mcr.microsoft.com/devcontainers/base:ubuntu",

          "features": {
            // AgentRecall is a .NET 10 global tool.
            "ghcr.io/devcontainers/features/dotnet:2": { "version": "10.0" }
          },

          // Persist the AgentRecall SQLite database across container rebuilds. The DB
          // lives under ~/.agentrecall, which is on the (rebuild-wiped) container
          // filesystem; backing it with a named Docker volume keeps the data until the
          // volume is explicitly removed (`docker volume rm agentrecall-data`).
          "mounts": [
            "source=agentrecall-data,target=/home/vscode/.agentrecall,type=volume"
          ],

          // Pin the data directory to the mounted path so the DB always lands on the
          // volume, regardless of which user/process runs the CLI or MCP server.
          "containerEnv": {
            "AGENTRECALL_AgentRecall__DataDirectory": "/home/vscode/.agentrecall"
          },

          "remoteEnv": {
            // So a globally-installed `agentrecall` tool is on PATH.
            "PATH": "${containerEnv:PATH}:/home/vscode/.dotnet/tools"
          },

          // Reinstalls AgentRecall and re-registers its MCP server on every rebuild.
          "postCreateCommand": "bash .devcontainer/agentrecall-post-create.sh"
        }

        """;

    /// <summary>
    /// Generates the setup script and, when the project has no
    /// <c>devcontainer.json</c>, a complete manifest. Returns a description of what
    /// was written and any manual steps the caller must apply to an existing manifest.
    /// </summary>
    /// <param name="projectRoot">Root directory whose <c>.devcontainer</c> is targeted.</param>
    public static DevcontainerInitResult Init(string projectRoot)
    {
        var devcontainerDir = Path.Combine(projectRoot, ".devcontainer");
        Directory.CreateDirectory(devcontainerDir);

        var scriptPath = Path.Combine(projectRoot, PostCreateRelativePath);
        var scriptExisted = File.Exists(scriptPath);
        File.WriteAllText(scriptPath, PostCreateScript);
        MakeExecutable(scriptPath);

        var jsonPath = Path.Combine(projectRoot, DevcontainerJsonRelativePath);
        if (File.Exists(jsonPath))
        {
            return new DevcontainerInitResult(
                ScriptPath: PostCreateRelativePath,
                ScriptOverwritten: scriptExisted,
                CreatedDevcontainerJson: false,
                DevcontainerJsonPath: DevcontainerJsonRelativePath,
                ManualSteps: ExistingManifestInstructions);
        }

        File.WriteAllText(jsonPath, DevcontainerJson);
        return new DevcontainerInitResult(
            ScriptPath: PostCreateRelativePath,
            ScriptOverwritten: scriptExisted,
            CreatedDevcontainerJson: true,
            DevcontainerJsonPath: DevcontainerJsonRelativePath,
            ManualSteps: null);
    }

    /// <summary>
    /// The keys a user must merge into an existing <c>devcontainer.json</c>, since
    /// AgentRecall does not rewrite a hand-maintained (JSONC) manifest.
    /// </summary>
    public static string ExistingManifestInstructions =>
        """
        Add (or merge) these keys into your existing .devcontainer/devcontainer.json:

          "features": {
            "ghcr.io/devcontainers/features/dotnet:2": { "version": "10.0" }
          },
          "mounts": [
            "source=agentrecall-data,target=/home/vscode/.agentrecall,type=volume"
          ],
          "containerEnv": {
            "AGENTRECALL_AgentRecall__DataDirectory": "/home/vscode/.agentrecall"
          },
          "remoteEnv": {
            "PATH": "${containerEnv:PATH}:/home/vscode/.dotnet/tools"
          },
          "postCreateCommand": "bash .devcontainer/agentrecall-post-create.sh"

        If you already use postCreateCommand, chain the script instead of replacing it, e.g.:
          "postCreateCommand": "<your existing command> && bash .devcontainer/agentrecall-post-create.sh"
        """;

    private static void MakeExecutable(string path)
    {
        if (OperatingSystem.IsWindows())
        {
            return;
        }

        // chmod 0755 so the dev container can invoke the script directly.
        File.SetUnixFileMode(
            path,
            UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute |
            UnixFileMode.GroupRead | UnixFileMode.GroupExecute |
            UnixFileMode.OtherRead | UnixFileMode.OtherExecute);
    }
}

/// <summary>Outcome of <see cref="DevcontainerScaffolder.Init"/>.</summary>
/// <param name="ScriptPath">Relative path of the generated setup script.</param>
/// <param name="ScriptOverwritten">Whether an existing script was overwritten.</param>
/// <param name="CreatedDevcontainerJson">Whether a fresh manifest was written.</param>
/// <param name="DevcontainerJsonPath">Relative path of the manifest.</param>
/// <param name="ManualSteps">Steps to apply to an existing manifest, or null.</param>
public sealed record DevcontainerInitResult(
    string ScriptPath,
    bool ScriptOverwritten,
    bool CreatedDevcontainerJson,
    string DevcontainerJsonPath,
    string? ManualSteps);
